plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.solver.speakingapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.solver.speakingapp"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    
    // 컴파일 시 자바와 코틀린의 버전을 17로 일치시킵니다.
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    // 가장 가볍고 안정적인 기초 라이브러리만 지정합니다.
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.alphacephei:vosk-android:0.3.47'
}
